[platformio]
default_envs = esp32dev

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -DCORE_DEBUG_LEVEL=0

[env:esp32dev]
build_src_filter = +<*> -<i2c_scan.cpp>
lib_deps =
    nrf24/RF24@^1.4.11
    olikraus/U8g2@^2.35.30

[env:scan]
build_src_filter = +<i2c_scan.cpp>
